# Generated by Django 6.0.5 on 2026-06-21 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('STRESSED', 'Stressed'), ('BORED', 'Bored'), ('CALM', 'Calm'), ('HAPPY', 'Happy'), ('SAD', 'Sad'), ('TIRED', 'Tired')], help_text='The primary mood selected by the user.', max_length=20)),
                ('food_description', models.TextField(help_text='Sensory description of flavors, textures, or warmth.')),
                ('food_image', models.ImageField(blank=True, help_text='Optional captured picture of the meal snapshot.', null=True, upload_to='mindful_meals/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food & Mood Log',
                'verbose_name_plural': 'Food & Mood Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_consistency_score', models.IntegerField(default=0, help_text='Percentage score tracking historical entry frequency (e.g., 85%).')),
                ('total_logs_count', models.PositiveIntegerField(default=0, help_text='Total calculated logs submitted over time.')),
                ('mood_correlation_data', models.JSONField(blank=True, default=dict, help_text='Structured analytics storage (e.g., mapping specific moods to sensory word frequencies).')),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insight Summary',
                'verbose_name_plural': 'Insight Summaries',
            },
        ),
    ]
