# Generated by Django 6.0.5 on 2026-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightsummary',
            name='mood_correlation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Maps moods to sensory word frequencies.'),
        ),
        migrations.AlterField(
            model_name='insightsummary',
            name='total_logs_count',
            field=models.PositiveIntegerField(default=0, help_text='Total logs submitted over time.'),
        ),
        migrations.AlterField(
            model_name='insightsummary',
            name='weekly_consistency_score',
            field=models.IntegerField(default=0, help_text='Percentage score (e.g. 85 = 85% consistency this week).'),
        ),
    ]
