# Generated by Django 6.0.5 on 2026-08-03 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_insightsummary_mood_correlation_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('emotion', models.CharField(choices=[('STRESSED', 'Stressed'), ('BORED', 'Bored'), ('CALM', 'Calm'), ('HAPPY', 'Happy'), ('SAD', 'Sad'), ('TIRED', 'Tired')], max_length=20)),
                ('gratitude', models.TextField()),
                ('reflection', models.TextField()),
                ('healing_intention', models.CharField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='journal/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
